services:
  web:
    image: ${ODOO_IMAGE}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PASSWORD_FILE: /run/secrets/postgresql_password
      HOST: ${DB_HOST}
      PORT: ${DB_PORT}
      USER: ${DB_USER}
      DATABASE: ${DB_NAME}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    secrets:
      - postgresql_password
    ports:
      - "127.0.0.1:18069:8069"
    networks:
      - internal
      - proxy

  db:
    image: ${DB_IMAGE}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - internal

volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: ./secrets/db_password

networks:
  internal:
  proxy:
    external: true